// Team Category Configuration
export const CATEGORY_CONFIG = {
    faculty: {
        label: 'Faculty',
        color: 'yellow', // Gold
        gradient: 'from-yellow-500 to-yellow-600',
        bgLight: 'bg-yellow-50',
        bgDark: 'bg-yellow-900/20',
        textLight: 'text-yellow-600',
        textDark: 'text-yellow-400',
        borderLight: 'border-yellow-200',
        borderDark: 'border-yellow-800',
    },
    leadership: {
        label: 'Leadership',
        color: 'purple',
        gradient: 'from-purple-500 to-purple-600',
        bgLight: 'bg-purple-50',
        bgDark: 'bg-purple-900/20',
        textLight: 'text-purple-600',
        textDark: 'text-purple-400',
        borderLight: 'border-purple-200',
        borderDark: 'border-purple-800',
    },
    finance: {
        label: 'Finance',
        color: 'green',
        gradient: 'from-green-500 to-green-600',
        bgLight: 'bg-green-50',
        bgDark: 'bg-green-900/20',
        textLight: 'text-green-600',
        textDark: 'text-green-400',
        borderLight: 'border-green-200',
        borderDark: 'border-green-800',
    },
    tech: {
        label: 'Technical Team',
        color: 'blue',
        gradient: 'from-blue-500 to-blue-600',
        bgLight: 'bg-blue-50',
        bgDark: 'bg-blue-900/20',
        textLight: 'text-blue-600',
        textDark: 'text-blue-400',
        borderLight: 'border-blue-200',
        borderDark: 'border-blue-800',
    },
    event_heads: {
        label: 'Event Management',
        color: 'red',
        gradient: 'from-red-500 to-red-600',
        bgLight: 'bg-red-50',
        bgDark: 'bg-red-900/20',
        textLight: 'text-red-600',
        textDark: 'text-red-400',
        borderLight: 'border-red-200',
        borderDark: 'border-red-800',
    },
    stage: {
        label: 'Stage Management',
        color: 'orange',
        gradient: 'from-orange-500 to-orange-600',
        bgLight: 'bg-orange-50',
        bgDark: 'bg-orange-900/20',
        textLight: 'text-orange-600',
        textDark: 'text-orange-400',
        borderLight: 'border-orange-200',
        borderDark: 'border-orange-800',
    },
    media: {
        label: 'Media',
        color: 'pink',
        gradient: 'from-pink-500 to-pink-600',
        bgLight: 'bg-pink-50',
        bgDark: 'bg-pink-900/20',
        textLight: 'text-pink-600',
        textDark: 'text-pink-400',
        borderLight: 'border-pink-200',
        borderDark: 'border-pink-800',
    },
    editors: {
        label: 'Creative Team',
        color: 'fuchsia',
        gradient: 'from-fuchsia-500 to-fuchsia-600',
        bgLight: 'bg-fuchsia-50',
        bgDark: 'bg-fuchsia-900/20',
        textLight: 'text-fuchsia-600',
        textDark: 'text-fuchsia-400',
        borderLight: 'border-fuchsia-200',
        borderDark: 'border-fuchsia-800',
    },
    pr: {
        label: 'Public Relations',
        color: 'indigo',
        gradient: 'from-indigo-500 to-indigo-600',
        bgLight: 'bg-indigo-50',
        bgDark: 'bg-indigo-900/20',
        textLight: 'text-indigo-600',
        textDark: 'text-indigo-400',
        borderLight: 'border-indigo-200',
        borderDark: 'border-indigo-800',
    },
    discipline: {
        label: 'Discipline',
        color: 'gray',
        gradient: 'from-gray-500 to-gray-600',
        bgLight: 'bg-gray-50',
        bgDark: 'bg-gray-900/20',
        textLight: 'text-gray-600',
        textDark: 'text-gray-400',
        borderLight: 'border-gray-200',
        borderDark: 'border-gray-800',
    },
} as const;

export type CategoryKey = keyof typeof CATEGORY_CONFIG;

// Helper function to get category config
export function getCategoryConfig(category: string) {
    return CATEGORY_CONFIG[category as CategoryKey] || CATEGORY_CONFIG.discipline;
}

// Category display order
export const CATEGORY_ORDER: CategoryKey[] = [
    'faculty',
    'leadership',
    'finance',
    'tech',
    'event_heads',
    'stage',
    'media',
    'editors',
    'pr',
    'discipline',
];
